#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)

	clear

	echo "--------------- Selamat datang di Server - IP: $MYIP ---------------"
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo "------------------------------------------------------------------------------"
	echo "Apa yang ingin Anda lakukan?"
	echo -e "\e[031;1m 1\e[0m) Buat Akaun SSH/OpenVPN (\e[34;1muser-add\e[0m)"
	echo -e "\e[031;1m 2\e[0m) Hapus Akaun SSH/OpenVPN (\e[34;1muser-del\e[0m)"
	echo -e "\e[031;1m 3\e[0m) Monitoring Dropbear (\e[34;1msh userlogin.sh 443\e[0m)"
	echo -e "\e[031;1m 4\e[0m) Monitor User OpenVPN (\e[34;1mcustomstatus\e[0m)"
	echo -e "\e[031;1m 5\e[0m) User Expired (\e[34;1muser-expire-list\e[0m)"
	echo -e "\e[031;1m 6\e[0m) Restart Dropbear (\e[34;1restart dropbear\e[0m)"
	echo -e "\e[031;1m 7\e[0m) Reboot Server (\e[34;1mreboot\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) Exit"
	echo ""
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
		1)
		clear
		user-add
		exit
		;;
		2)
		clear
		user-del
		exit
		;;
		3)
		clear
		sh userlogin.sh 443
		exit
		;;
		4)
		clear
		customstatus
		exit
		;;
		5)
		clear
		user-expire-list
		exit
		;;
		6)
		clear
		service dropbear restart
		exit
		;;
		7)
		clear
		reboot
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done

cd ~/
rm -f /root/IP
