#!/bin/bash

# go to root
cd

# update
yum -y update

# install monitor dropbear login
wget https://raw.githubusercontent.com/syahz86/VPN/master/conf/userlogin.sh
chmod +x userlogin.sh

# download script
cd /usr/bin
wget https://raw.githubusercontent.com/syahz86/Centos/master/user-add && chmod +x user-add
wget https://raw.githubusercontent.com/syahz86/Centos/master/user-expire-list && chmod +x user-expire-list
wget https://raw.githubusercontent.com/syahz86/Centos/master/user-active-list && chmod +x user-active-list
wget https://raw.githubusercontent.com/syahz86/VPN/master/menu && chmod +x menu

# info
clear
echo -e "Please type \e[1;33;44mmenu\e[0m for options"

echo "==============================================="
